### ISSUE TITLE
Bug with valid-describe

### ISSUE THREAD

**Issue by SimeonC** [jest-community/eslint-plugin-jest#105]
I found this bug when converting some tests from another repo.

Sample test:
```js
describe('test name', () =>
  test('some test', () => {...})
);
```
Will cause the following error:
```
/eslint-plugin-jest/rules/valid-describe.js:79
          callbackFunction.body.body.forEach(node => {
                                    ^

TypeError: Cannot read property 'forEach' of undefined
    at CallExpression (/eslint-plugin-jest/rules/valid-describe.js:79:37)
    at listeners.(anonymous function).forEach.listener (/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/eslint/lib/code-path-analysis/code-path-analyzer.js:606:23)
    at Traverser.enter (/eslint/lib/linter.js:955:32)
    at Traverser.__execute (/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/node_modules/estraverse/estraverse.js:501:28)
```

```
"eslint": "4.9.0",
"eslint-config-airbnb": "^16.1.0",
"eslint-import-resolver-babel-module": "^4.0.0",
"eslint-plugin-import": "^2.11.0",
"eslint-plugin-jest": "^21.15.0",
"eslint-plugin-jsx-a11y": "^6.0.3",
"eslint-plugin-promise": "^3.7.0",
"eslint-plugin-react": "^7.7.0"
```

**Comment by SimenB** [comment]
Thanks for the report and the minimal reproduction!
