### ISSUE TITLE
[BUG]: Unexpected token '?'

### ISSUE THREAD

**Issue by Beladric** [jest-community/eslint-plugin-jest#1336]
Greetings,

I'm facing to a strange issue, my ESLint cannot load `eslint-plugin-jest` due to a Syntax Error in a file of the library.

This is the error message :
`ESLint: syntaxError:Failed to lad plugin 'jest' declared in '.eslintrc.json#overrides[0]':Unexpected token '?'`

When I'm looking for more details about the error, I have the following logs :
```shell
SyntaxError: Failed to load plugin 'jest' declared in '.eslintrc.json#overrides[0]': Unexpected token '?'
Referenced from: /MyProject/.eslintrc.json

/MyProject/node_modules/eslint-plugin-jest/lib/rules/utils/parseJestFnCall.js:55
  const globalAliases = ((_context$settings$jes = context.settings.jest) === null || _context$settings$jes === void 0 ? void 0 : _context$settings$jes.globalAliases) ?? {};
                                                                                                                                                                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/MyProject/node_modules/eslint-plugin-jest/lib/rules/utils/misc.js:14:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Process finished with exit code -1

```

My `eslint-plugin-jest` version is `27.2.1` and my `eslint` version is `8.33.0`.

I hope someone can help me,
Kind regards, Kilian GOËTZ.

**Comment by SimenB** [comment]
You need to use node 14 or later

**Comment by Beladric** [comment]
Hello @SimenB My node version is `19.5.0`.

![image](https://user-images.githubusercontent.com/37240228/215341140-20872f57-828d-4d1c-99c7-d327e8a61282.png)

**Comment by SimenB** [comment]
Not when you invoke ESLint as your error is a syntax error on `??`, which has been supported since Node 14.0: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

**Comment by Beladric** [comment]
@SimenB Thanks for your help ! 

It's working, you were right. I had two Node.js installed, one in v12 and the other in 19.5 .
