### ISSUE TITLE
Upgrade from 22.5.1 to 22.6.0 fails with error `/bin/sh: 1: babel: not found`

### ISSUE THREAD

**Issue by tmorehouse** [jest-community/eslint-plugin-jest#263]
After upgrading to 22.6.0, we get the following build error when installing eslint-plugin-jest:

```bash
error /root/project/bootstrap-vue/node_modules/eslint-plugin-jest: Command failed.
Exit code: 1
Command: yarn build
Arguments: 
Directory: /root/project/bootstrap-vue/node_modules/eslint-plugin-jest
Output:
yarn run v1.13.0
$ babel --extensions .js,.ts src --out-dir lib
/bin/sh: 1: babel: not found
error Command failed with exit code 127.
```

Fails due to the `postinstall` command introduced via #257 which tries to compile files with babel.

**Comment by tmorehouse** [comment]
Maybe you need to be explicit with the path to `babel` (i.e. `node_modules/.bin/babel`)

**Comment by quarties** [comment]
I can confirm that issue - rolling back to version `22.5.1` can fix that.

**Comment by mdavis199** [comment]
I think the problem is because `@babel/cli` is listed as a `devDependency`; but `babel` is being used during the installation of `eslint-plugin-jest` when the post-install script is run.  So, babel is no longer a devDependency; it's required for installation.

**Comment by swissspidy** [comment]
I am getting a similar issue, but in my case it's `yarn` that is not installed, not `babel`. So it fails earlier.

**Comment by shazron** [comment]
This is the commit that introduced the build issue I believe: https://github.com/jest-community/eslint-plugin-jest/pull/257/commits
I don't have yarn installed globally, so it fails

**Comment by ranyitz** [comment]
Running build during `pretest` solves the issue while enabling transpilation before running the tests. This PR should do the trick -https://github.com/jest-community/eslint-plugin-jest/pull/265

**Comment by tmorehouse** [comment]
Seeing a new error now when we run lint on our own packages:

```
#!/bin/bash -eo pipefail
yarn lint
yarn run v1.13.0
$ eslint --ext .js,.md,.vue ./
Error: Cannot find module '@typescript-eslint/experimental-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/project/bootstrap-vue/node_modules/eslint-plugin-jest/lib/rules/tsUtils.js:10:26)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by SimenB** [comment]
Oops, it's a dev dep not a regular dep. Mind sending a PR? Workaround is to install it yourself. I'm stuck on mobile (albeit with internet), so not the easiest to fix myself

**Comment by SimenB** [comment]
Edit should be fixed whenever CI publishes the next version

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v22.6.2

Hopefully things work now! 🤞

**Comment by tmorehouse** [comment]
Nope :(

```
#!/bin/bash -eo pipefail
yarn lint
yarn run v1.13.0
$ eslint --ext .js,.md,.vue ./
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/project/bootstrap-vue/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```
