### ISSUE TITLE
Build fails, complaining it can not find '@typescript-eslint/experimental-utils'

### ISSUE THREAD

**Issue by wlach** [jest-community/eslint-plugin-jest#266]
A renovate PR bumping the version of this package used in our project iodide (iodide-project/iodide#1855) is failing, complaining about some type of missing typescript package. Does an additional depdendency need to be specified in this project's package.json?

```
Error: Cannot find module '@typescript-eslint/experimental-utils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/iodide/node_modules/eslint-plugin-jest/lib/rules/tsUtils.js:10:26)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by nightink** [comment]
+1

**Comment by SimenB** [comment]
Bah, so sorry about this mess!

#267

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v22.6.2
