### ISSUE TITLE
"Cannot read property 'meta' of undefined" after update to 22.6.2

### ISSUE THREAD

**Issue by hbroer** [jest-community/eslint-plugin-jest#268]
`Cannot read property 'meta' of undefined` after update to 22.6.2

```
> eslint --ext .ts,.js ./

TypeError: Cannot read property 'meta' of undefined
    at rules.forEach (C:\Users\[...]\projects\ioc\node_modules\eslint\lib\cli.js:97:34)
    at Map.forEach (<anonymous>)
    at printResults (C:\Users\[...]\projects\ioc\node_modules\eslint\lib\cli.js:96:11)
    at Object.execute (C:\Users\[...]\projects\ioc\node_modules\eslint\lib\cli.js:217:17)
    at Object.<anonymous> (C:\Users\[...]\projects\ioc\node_modules\eslint\bin\eslint.js:78:28)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Greenkeeper is going mad on my repo ;)

Repository: [github.com/owja/ioc](https://github.com/owja/ioc)

**Comment by hbroer** [comment]
Downgrading to `22.5.1` and it works again. I will pin that version.

**Comment by SimenB** [comment]
Should be a new release whenever https://www.githubstatus.com/incidents/nf4gcjtcsqdb is gone
