### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'node_modules/eslint-plugin-jest/lib/index.js'

### ISSUE THREAD

**Issue by arkaydeus** [jest-community/eslint-plugin-jest#270]
Tried using 22.6.2 but got:
https://github.com/jest-community/eslint-plugin-jest/issues/268

So downgraded to 22.5.1 and get the following:
```
Error: ENOENT: no such file or directory, open '/home/user/project/bfrc2/node_modules/eslint-plugin-jest/lib/index.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:721:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by tmorehouse** [comment]
#266

You'll need to downgrade to 22.5.1

**Comment by SimenB** [comment]
Should be a new release whenever https://www.githubstatus.com/incidents/nf4gcjtcsqdb is gone

**Comment by arkaydeus** [comment]
Thanks!

**Comment by AndyOGo** [comment]
I get a similar error with `"eslint-plugin-jest": "^22.17.0",`:

```sh
ESLint: ENOENT: no such file or directory, open './aletheia/node_modules/eslint-plugin-jest/index.js'. Please see the 'ESLint' output channel for details.
```

**Comment by AndyOGo** [comment]
@SimenB Thanks for your reply, I just edited my comment above.
All fine, had to re-install the ESLint plugin for VSCode 😕
