### ISSUE TITLE
Unhandled error with `prefer-to-be-null`

### ISSUE THREAD

**Issue by alexlrobertson** [jest-community/eslint-plugin-jest#29]
My linter crashes occasionally when using `prefer-to-be-null` with an expectation without a value.

```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at expectToEqualCase (/project/node_modules/eslint-plugin-jest/rules/util.js:40:17)
    at CallExpression (/project/node_modules/eslint-plugin-jest/rules/prefer_to_be_null.js:10:41)
    at listeners.(anonymous function).forEach.listener (/project/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/project/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/project/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/project/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/project/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter (/project/node_modules/eslint/lib/linter.js:956:32)
```

```jsx
expect(store.getFilters()).toEqual();
```

**Comment by SimenB** [comment]
Fixed in v21.4.1, thanks for the report!
