### ISSUE TITLE
Rule no-identical-title fails with JS error

### ISSUE THREAD

**Issue by unkhz** [jest-community/eslint-plugin-jest#437]
The following failure is shown given the rule is enabled and the default formatter is used (stylish). Using the json formatter works correctly.
```
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at messages.map.message (/Users/unkhz/Work/example/node_modules/eslint/lib/formatters/stylish.js:68:37)
    at Array.map (<anonymous>)
    at results.forEach.result (/Users/unkhz/Work/example/node_modules/eslint/lib/formatters/stylish.js:53:22)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/unkhz/Work/example/node_modules/eslint/lib/formatters/stylish.js:38:13)
    at printResults (/Users/unkhz/Work/example/node_modules/eslint/lib/cli.js:91:20)
    at Object.execute (/Users/unkhz/Work/example/node_modules/eslint/lib/cli.js:201:17)
    at Object.<anonymous> (/Users/unkhz/Work/example/node_modules/eslint/bin/eslint.js:74:28)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

My config is this
```
module.exports = {
  env: {
    node: true,
    es6: true,
    'jest/globals': true
  },
  plugins: ['jest'],
  rules: {
    'jest/no-identical-title': ['error']
  }
}
```

And the failing test suite is this
```
describe('thing', () => {
  it('duplicate name of test case', () => {
    expect(true).toEqual(true)
  })

  it('duplicate name of test case', () => {
    expect(true).toEqual(true)
  })
})
```

Workaround is to disable the rule
```
{
  rules: {
    'jest/no-identical-title': ['off']
  }
}
```

Version of `eslint`: v4.10.0
Version of `eslint-plugin-jest`: 22.20.0

**Comment by G-Rath** [comment]
I'll try to have a look into this, but I'm pretty sure this isn't related to us, since the stacktrace contains (ironically) no trace of `eslint-plugin-jest`.

**Comment by G-Rath** [comment]
I've looked into this, and can reproduce it with the exact `eslint` version you mentioned.

The line itself is this:

```
                return [
                    "",
                    message.line || 0,
                    message.column || 0,
                    messageType,
                    message.message.replace(/([^ ])\.$/, "$1"),
                    chalk.dim(message.ruleId || "")
                ];
```

It's b/c of the `message.message.replace`, but as I said we don't support `eslint@4`; eslint must have changed how they outputted messages in later versions, so I don't think we could fix this even if we wanted to.

However, there is good news for you - this doesn't happen on `eslint@4.15.0`, which your package constraint does allow you to upgrade to :)

**Comment by unkhz** [comment]
Makes sense. I also noticed that upgrading even the version 4 to the latest (4.19.1) fixes the issue.
