### ISSUE TITLE
error upgrading from 22.7.0 to 23.1.1

### ISSUE THREAD

**Issue by ldeveber** [jest-community/eslint-plugin-jest#492]
I'm seeing this error loading the jest plugin in my config. Any ideas?

```bash
Error: Failed to load plugin 'jest' declared in 'aaa-static/.eslintrc.js': Cannot find module 'eslint-plugin-jest'
Require stack:
- ~/projects/aaa/__placeholder__.js

Error: Failed to load plugin 'jest' declared in 'aaa-static/.eslintrc.js': Cannot find module 'eslint-plugin-jest'
Require stack:
- ~/projects/aaa/__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.resolve (~/projects/aaa/aaa-static/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (~/projects/aaa/aaa-static/node_modules/eslint/lib/cli-engine/config-array-factory.js:957:39)
    at names.reduce (~/projects/aaa/aaa-static/node_modules/eslint/lib/cli-engine/config-array-factory.js:846:33)
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (~/projects/aaa/aaa-static/node_modules/eslint/lib/cli-engine/config-array-factory.js:842:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (~/projects/aaa/aaa-static/node_modules/eslint/lib/cli-engine/config-array-factory.js:665:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (~/projects/aaa/aaa-static/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
Process finished with exit code -1
```

Here is my config file
```js
module.exports = {
  extends: [ 'react-app' ],
  root: true,
  settings: {
    react: {
      version: '16.10'
    }
  },
  plugins: [ 'jest' ],
  rules: {
    semi: [ 'warn', 'always' ],
    'no-fallthrough': 'warn',
    'no-undef': 'warn', // !
    'no-unused-vars': ['warn', {'args': 'after-used'}],
    'prefer-const': 'warn',
    'jest/expect-expect': 'error',
    'jest/no-commented-out-tests': 'error',
    'jest/valid-expect': 'error',
  }
};
```

**Comment by G-Rath** [comment]
That error indicates that you've not got `eslint-plugin-jest` installed.

Could you provide a copy of your `package.json`, and try removing `node_modules` & re-installing? (you can do this in one command via `npm ci` if you're using `npm`).

**Comment by ldeveber** [comment]
Package.json:

```
{
  "name": "aaa-static",
  "version": "0.0.1",
  "private": true,
  "license": "UNLICENSED",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.15",
    "@fortawesome/free-regular-svg-icons": "^5.8.1",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "ag-grid-community": "21.2.2",
    "ag-grid-enterprise": "21.2.2",
    "ag-grid-react": "21.2.2",
    "airbrake-js": "^1.6.7",
    "axios": "^0.19.0",
    "bootstrap": "^4.3.1",
    "cross-fetch": "^3.0.2",
    "i18next": "^17.0.18",
    "immer": "^3.1.1",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "prop-types": "^15.6.2",
    "react": "^16.10.1",
    "react-checkbox-tree": "^1.5.1",
    "react-datepicker": "2.8.0",
    "react-dom": "^16.4.1",
    "react-i18next": "^10.13.1",
    "react-moment": "^0.9.2",
    "react-redux": "^7.0.2",
    "react-router": "5.0.1",
    "react-router-dom": "5.0.1",
    "react-select": "^3.0.4",
    "react-stomp": "^4.1.0",
    "react-toastify": "^5.1.0",
    "reactstrap": "^8.0.0",
    "reduce-reducers": "^1.0.4",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/polyfill": "^7.6.0",
    "@typescript-eslint/eslint-plugin": "2.x",
    "@typescript-eslint/parser": "2.x",
    "babel-eslint": "10.x",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.4",
    "babel-preset-react-app": "^9.0.1",
    "clean-webpack-plugin": "^2.0.1",
    "concurrently": "^4.1.0",
    "create-react-component-folder": "^0.1.26",
    "cross-env": "^5.2.0",
    "css-loader": "^2.1.0",
    "cssnano": "^4.1.8",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "enzyme-to-json": "^3.3.5",
    "eslint": "6.x",
    "eslint-config-react-app": "^5.0.2",
    "eslint-loader": "^3.0.2",
    "eslint-plugin-flowtype": "3.x",
    "eslint-plugin-import": "2.x",
    "eslint-plugin-jest": "^23.1.1",
    "eslint-plugin-jsx-a11y": "6.x",
    "eslint-plugin-react": "7.x",
    "eslint-plugin-react-hooks": "1.x",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^24.7.1",
    "jest-environment-enzyme": "^7.0.2",
    "jest-enzyme": "^7.0.2",
    "jest-nyancat-reporter": "^2.0.0",
    "jest-skipped-reporter": "^0.0.4",
    "mini-css-extract-plugin": "^0.6.0",
    "moxios": "^0.4.0",
    "node-sass-chokidar": "^1.3.0",
    "npm-run-all": "^4.1.5",
    "postcss-loader": "^3.0.0",
    "react-dev-utils": "^8.0.0",
    "redux-mock-store": "^1.5.3",
    "redux-promise-middleware": "^6.1.0",
    "sass-loader": "^7.1.0",
    "speed-measure-webpack-plugin": "^1.3.1",
    "style-loader": "^0.23.1",
    "svg-inline-loader": "^0.8.0",
    "uglifyjs-webpack-plugin": "^2.1.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.28.2",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14",
    "webpack-merge": "^4.1.5",
    "webpackbar": "^3.1.4"
  },
  "engines": {
    "node": "^10.0.0"
  },
  "scripts": {
    ...
  }
}
```

Result:
```
```

**Comment by G-Rath** [comment]
Interesting - maybe it's related to `react-app`...?

Could you provide some information on the file structure of your project, and the exact command you're using to invoke `eslint`?

**Comment by ldeveber** [comment]
This is for an electron app with a java backend, where we have two different jest suites. File structure is like:

- aaa
  - package.json
  - node_modules
  - aaa-static
    - node_modules
    - src
    - test
    - package.json
  - aaa-svc

Command is `eslint ./src ./tests` which is ran from aaa-static.

We are currently only trying to lint `aaa-static`.

**Comment by G-Rath** [comment]
Could you try installing `eslint-plugin-jest` at the top level, and seeing if that fixes it?

I suspect the issue might be b/c `eslint` looks at the top level `node_modules` - if that is correct behaviour is another story we can dive into afterwards; for now it's a quick & easy thing to test :)

**Comment by G-Rath** [comment]
@ldeveber are you still having problems, or can I close this? 🙂

**Comment by ldeveber** [comment]
Sorry, I did not get a chance to try this again yet! I will try today

**Comment by ldeveber** [comment]
I'm still getting the same error :(

**Comment by G-Rath** [comment]
@ldeveber would you be able to provide your full `package.json` & lock?

**Comment by ldeveber** [comment]
Yes, I'm still seeing the errors. Sorry for the super long delay :(

<details>
  <summary>aaa package.json</summary>

```json
{
  "name": "aaa",
  "main": "electron/index.js",
  "license": "UNLICENSED",
  "scripts": {
    "start": "eslint ./electron && electron ./electron",
    "build-server": "node buildscripts/build-server.js",
    "build-installer": "node buildscripts/build-installer.js",
    "build": "yarn run build-staging",
    "build-staging": "eslint ./electron && BUILD_PROFILE=STAGING npm-run-all clean build-server build-installer",
    "build-staging-mac": "eslint ./electron && PLAT=mac BUILD_PROFILE=STAGING npm-run-all clean build-server build-installer",
    "build-staging-win": "eslint ./electron && PLAT=win BUILD_PROFILE=STAGING npm-run-all clean build-server build-installer",
    "build-prod": "eslint ./electron && npm-run-all clean build-server build-installer",
    "build-prod-mac": "eslint ./electron && PLAT=mac BUILD_PROFILE=PRODUCTION npm-run-all clean build-server build-installer",
    "build-prod-win": "eslint ./electron && PLAT=win BUILD_PROFILE=PRODUCTION npm-run-all clean build-server build-installer",
    "clean": "rimraf dist",
    "cy:open": "eslint ./cypress && cypress open",
    "cy:run": "eslint ./cypress && cypress run",
    "start-and-test": "start-server-and-test start http://localhost:8080 cy:run",
    "sync-version": "sync-package-pom ./package.json aaa-svc/pom.xml && cd aaa-static && yarn version --new-version $npm_package_version --no-commit-hooks --no-git-tag-version",
    "cy:run-ci": "eslint ./cypress && cypress run --browser chrome --config video=false numTestsKeptInMemory=0",
    "start-and-test-ci": "start-server-and-test start http://localhost:8080 cy:run-ci",
    "junit-merge": "junit-merge"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  },
  "engines": {
    "node": "^12.15.0"
  },
  "devDependencies": {
    "aws-sdk": "^2.656.0",
    "cypress": "^4.3.0",
    "cypress-file-upload": "^4.0.4",
    "cypress-log-to-output": "^1.0.8",
    "electron": "8.2.1",
    "electron-builder": "^22.4.1",
    "electron-notarize": "^0.3.0",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "faker": "^4.1.0",
    "jest-junit": "^10.0.0",
    "leasot": "^10.2.0",
    "mocha-circleci-reporter": "^0.0.3",
    "npm-run-all": "^4.1.5",
    "replace-in-file": "^5.0.2",
    "rimraf": "^3.0.2",
    "shelljs": "^0.8.2",
    "signcode": "^1.0.0",
    "start-server-and-test": "^1.10.11",
    "sync-package-pom": "^1.0.1",
    "wait-on": "^4.0.2",
    "yaml": "^1.8.3"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "child_process": "^1.0.2",
    "cross-env": "^7.0.2",
    "electron-debug": "^3.0.1",
    "electron-is-dev": "^1.2.0",
    "electron-log": "^4.1.1",
    "electron-updater": "^4.2.5",
    "eslint-plugin-jest": "^23.8.2",
    "fs-extra": "^9.0.0",
    "fs-finder": "^1.8.1",
    "inly": "^4.0.5",
    "moment": "^2.24.0",
    "os": "^0.1.1",
    "portfinder": "^1.0.25",
    "process": "^0.11.10",
    "promise-retry": "^1.1.1"
  }
}
```
</details>

<details>
  <summary>aaa eslintrc.js</summary>

```js
module.exports = {
  root: true,
  // extends: 'standard',
  env: {
    es6: true,
    node: true
  },
  rules: {
    'eol-last': [ 'warn', 'always' ],

    // Best practices, doing things "the right way" to avoid common errors
    // https://eslint.org/docs/rules/#best-practices
    'consistent-return': 'warn', // !
    'default-case': 'warn', // !
    'dot-notation': 'warn',
    'eqeqeq': 'error', // !
    'no-eq-null': 'warn', // !
    'no-eval': 'warn',
    'no-fallthrough': 'warn',
    'no-global-assign': 'warn',
    'no-implicit-globals': 'warn',
    'no-invalid-this': 'warn', // !
    'no-loop-func': 'error',
    'no-multi-assign': 'warn',
    'no-new-func': 'warn',
    'no-new-wrappers': 'warn',
    'no-useless-call': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-return': 'warn',
    semi: [ 'warn', 'always' ],
    'wrap-iife': ['error', 'any'],

    // Rules that help catch possible errors
    // https://eslint.org/docs/rules/#possible-errors
    'for-direction': 'warn',
    'no-await-in-loop': 'warn',
    'no-cond-assign': ['error', 'except-parens'],

    // Helpful warnings to assist in migrating to ES6+
    // https://eslint.org/docs/rules/#ecmascript-6
    'arrow-body-style': 'off',
    'arrow-spacing': 'warn',
    'comma-dangle': 'off',
    'no-empty-pattern': 'warn',
    'no-this-before-super': 'error',
    'no-var': 'warn',
    'object-shorthand': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': 'warn',
    'prefer-destructuring': 'warn',
    'prefer-rest-params': 'warn',
    'prefer-spread': 'warn',
    'prefer-template': 'warn',

    // Rules related to variables
    // https://eslint.org/docs/rules/#variables
    'no-shadow': 'warn', // !
    'no-shadow-restricted-names': 'warn',
    'no-undef-init': 'warn',
    'no-undef': 'warn', // !
    'no-unused-vars': ['warn', {'args': 'after-used'}],
    'no-use-before-define': 'warn',
    'no-restricted-imports': [
      'error',
      {
        paths: [
          {
            name: 'lodash.isequal',
            message:
              'Lodash modularised (and lodash < 4.17.11) have CVE vulnerabilities. Please use tree-shakeable imports like lodash/xxx instead',
          },
          {
            name: 'lodash.mergewith',
            message:
              'Lodash modularised (and lodash < 4.17.11) have CVE vulnerabilities. Please use tree-shakeable imports like lodash/xxx instead',
          },
          {
            name: 'lodash.pick',
            message:
              'Lodash modularised (and lodash < 4.17.11) have CVE vulnerabilities. Please use tree-shakeable imports like lodash/xxx instead',
          },
        ],
        // catch-all for any lodash modularized. The CVE is listed against the entire family for lodash < 4.17.11
        patterns: ['lodash.*'],
      },
    ]
  }
};
```
</details>

<details>
  <summary>aaa-static package.json</summary>

```json
{
  "name": "aaa-static",
  "version": "1.0.856",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "start": "yarn run todo && concurrently \"cross-env NODE_ENV=development webpack-dev-server --hot --inline --env=dev\" \"cross-env NODE_ENV=test jest --watch --coverage\"",
    "start-ci": "cross-env NODE_ENV=development webpack-dev-server --hot --inline --env=dev",
    "build": "cross-env NODE_ENV=production webpack -p --env=prod --display=minimal",
    "deploy": "eslint ./src ./tests && cross-env DEPLOY_MODE=true yarn run build",
    "todo": "leasot \"./**/*\" --skip-unsupported -i \"node_modules/**/*\" \"coverage/**/*\" \"build/**/*\" -x",
    "test": "yarn run todo && eslint ./src ./tests && cross-env NODE_ENV=test jest --coverage",
    "test:watch": "cross-env NODE_ENV=test jest --watch",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public -o ./build/storybook-static",
    "build-storybook-ci": "yarn run build-storybook && cd build && bestzip dt-storybook-$npm_package_version.zip storybook-static",
    "storybook-ci-test": "start-storybook --smoke-test --ci && build-storybook --quiet -s public -o ./build/storybook-static"
  },
  "dependencies": {
    "@airbrake/browser": "^1.0.7",
    "@auth0/auth0-spa-js": "^1.6.4",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-regular-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "@validityhq/styleguide": "^0.1.3",
    "ag-grid-community": "^23.0.2",
    "ag-grid-enterprise": "^23.0.2",
    "ag-grid-react": "^23.0.3",
    "axios": "^0.19.0",
    "chart.js": "^2.9.3",
    "chartjs-plugin-doughnutlabel": "^2.0.3",
    "classnames": "^2.2.6",
    "cross-fetch": "^3.0.2",
    "history": "^4.10.1",
    "i18next": "^19.4.0",
    "immer": "^5.3.2",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.6.2",
    "react": "^16.13.1",
    "react-chartjs-2": "^2.9.0",
    "react-checkbox-tree": "^1.6.0",
    "react-dom": "^16.13.1",
    "react-i18next": "^11.3.4",
    "react-moment": "^0.9.7",
    "react-redux": "^7.0.2",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "react-select": "^3.1.0",
    "react-simple-tree-menu": "^1.1.14",
    "react-stomp": "^5.0.0",
    "react-toastify": "^5.5.0",
    "react-window": "^1.8.5",
    "reduce-reducers": "^1.0.4",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "styled-components": "^5.1.0",
    "uuid": "^7.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/polyfill": "^7.8.7",
    "@sambego/storybook-state": "^2.0.1",
    "@storybook/addon-a11y": "^5.3.18",
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-backgrounds": "^5.3.18",
    "@storybook/addon-docs": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-links": "^5.3.18",
    "@storybook/addon-storyshots": "^5.3.18",
    "@storybook/addon-storysource": "^5.3.18",
    "@storybook/addon-viewport": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/core": "^5.3.18",
    "@storybook/react": "^5.3.18",
    "@storybook/source-loader": "^5.3.18",
    "addon-redux": "^1.0.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.3.0",
    "babel-loader": "^8.1.0",
    "babel-preset-react-app": "^9.1.2",
    "bestzip": "^2.1.5",
    "clean-webpack-plugin": "^3.0.0",
    "concurrently": "^5.0.2",
    "create-react-component-folder": "^0.2.0",
    "cross-env": "^7.0.2",
    "css-loader": "^3.5.1",
    "cssnano": "^4.1.8",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.3.5",
    "eslint": "^6.8.0",
    "eslint-config-react-app": "^5.2.1",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-flowtype": "^4.7.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jest": "23.8.2",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^3.0.0",
    "file-loader": "^6.0.0",
    "html-webpack-plugin": "^4.2.0",
    "jest": "^25.3.0",
    "jest-environment-enzyme": "^7.1.2",
    "jest-enzyme": "^7.1.2",
    "jest-nyancat-reporter": "^2.0.0",
    "jest-skipped-reporter": "^0.0.5",
    "jest-slow-test-reporter": "^1.0.0",
    "jest-styled-components": "^7.0.2",
    "leasot": "^10.2.0",
    "mini-css-extract-plugin": "^0.9.0",
    "moxios": "^0.4.0",
    "node-sass-chokidar": "^1.4.0",
    "npm-run-all": "^4.1.5",
    "postcss-loader": "^3.0.0",
    "react-dev-utils": "^10.2.1",
    "react-test-renderer": "^16.13.1",
    "redux-mock-store": "^1.5.3",
    "redux-promise-middleware": "^6.1.0",
    "sass-loader": "^8.0.2",
    "speed-measure-webpack-plugin": "^1.3.1",
    "storybook-addon-i18n": "^5.1.13",
    "storybook-react-router": "^1.0.8",
    "style-loader": "^1.1.3",
    "svg-inline-loader": "^0.8.0",
    "uglifyjs-webpack-plugin": "^2.1.1",
    "url-loader": "^4.1.0",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14",
    "webpack-merge": "^4.1.5",
    "webpackbar": "^4.0.0"
  },
  "peerDependencies": {
    "react-is": "^16.13.1",
    "regenerator-runtime": "^0.13.5"
  },
  "engines": {
    "node": "^12.15.0"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
</details>

<details>
  <summary>aaa-static eslintrc.js</summary>

```js
module.exports = {
  extends: 'eslint-config-react-app',
  root: true,
  settings: {
    react: {
      version: '16.13'
    }
  },
  plugins: [ 'jest' ],
  env: {
    'jest/globals': true
  },
  rules: {
    'eol-last': [ 'warn', 'always' ],
    semi: [ 'warn', 'always' ],
    'no-fallthrough': 'warn',
    'no-undef': 'warn', // !
    'no-unused-vars': ['warn', {'args': 'after-used'}],
    'prefer-const': 'warn',
    'jest/expect-expect': 'error',
    'jest/no-commented-out-tests': 'error',
    'jest/valid-expect': 'error',
    'no-restricted-imports': [
      'error',
      {
        paths: [
          {
            name: 'lodash.isequal',
            message:
              'Lodash modularised (and lodash < 4.17.11) have CVE vulnerabilities. Please use tree-shakeable imports like lodash/xxx instead',
          },
          {
            name: 'lodash.mergewith',
            message:
              'Lodash modularised (and lodash < 4.17.11) have CVE vulnerabilities. Please use tree-shakeable imports like lodash/xxx instead',
          },
          {
            name: 'lodash.pick',
            message:
              'Lodash modularised (and lodash < 4.17.11) have CVE vulnerabilities. Please use tree-shakeable imports like lodash/xxx instead',
          },
        ],
        // catch-all for any lodash modularized. The CVE is listed against the entire family for lodash < 4.17.11
        patterns: ['lodash.*'],
      },
    ],

    // based on sonar rules
    quotes: [ 'warn', 'single' ],
    'jsx-quotes': [ 'warn', 'prefer-double' ],
  }
};
```
</details>

**Comment by ldeveber** [comment]
Oops, just realized you wanted the .locks too.

aaa yarn.lock: https://pastebin.com/Eg5kFxSM

aaa-static yarn.lock triggered the pastebin limit because its too big :(

**Comment by G-Rath** [comment]
Would you be able to put this all into a small self contained repo that reproduces the issue?

**Comment by ldeveber** [comment]
I have just upgraded to 23.20.0 and it seems to be working now!

**Comment by SimenB** [comment]
Nice! So we can close this?

**Comment by ldeveber** [comment]
Yes!
