### ISSUE TITLE
Error when adding to project.

### ISSUE THREAD

**Issue by Ionut-Milas** [jest-community/eslint-plugin-jest#5]
I get this error:

```
SyntaxError: Unexpected token )

/Users/....../node_modules/eslint-plugin-jest/rules/prefer_to_have_length.js:27
            );
            ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/..../node_modules/eslint-plugin-jest/index.js:6:28)
    at Module._compile (module.js:573:32)
Process finished with exit code -1

```

**Comment by SimenB** [comment]
Oh, there's a trailing comma, there! Sorry

**Comment by SimenB** [comment]
Fix published as 21.3.1

**Comment by thymikee** [comment]
Moving fast! 🚀

**Comment by Ionut-Milas** [comment]
Yes, sadly there is a new error now.
```
TypeError: Cannot read property 'name' of undefined
/eslint-plugin-jest/rules/prefer_to_have_length.js:20:56)
```

**Comment by SimenB** [comment]
Interesting, do you have a repro?

**Comment by Ionut-Milas** [comment]
this is what I test:

```
describe( "quack", () => {
    const quack = actions.quack( );
    const initialState = false;

    const result = reducer( initialState, quack );

    it( "should quack", () => {
        expect( result ).toBe( true );
    } );
} );
```
Basically a reducer that returns true.

This is the .eslintrc
```
{
    "extends": ["fortech"],
    "env": {
      "jest/globals": true
    },
    "plugins": [
        "fp",
        "compat",
        "jest"
    ],
    "rules": {
        // code complexity: http://www.tutorialspoint.com/software_testing_dictionary/cyclomatic_complexity.htm
        "complexity": [ 1, 4 ],
        "comma-dangle": [ 2, "never" ],
        "no-param-reassign": 1,
        "no-mixed-operators": 1,
        "no-plusplus": 1,
        "no-restricted-properties": 1,
        "no-script-url": 1,

        "react/prop-types": 1,
        "react/require-default-props": 1,
        "react/forbid-prop-types": 1,
        "react/no-unused-prop-types": 1,
        "react/no-unescaped-entities": 1,
        "react/no-array-index-key": 1,

        "jsx-a11y/no-static-element-interactions": 1,

        "import/extensions": 0,
        "import/first": 1,

        //immutable
        "fp/no-mutating-assign": [ 0 ],
        "fp/no-mutating-methods": [ 0 ],
        "fp/no-mutation": [ 0, { "exceptions": [ { "property": "propTypes" }, { "property": "prefetch" } ] } ],

        //compatibility
        "compat/compat": 1,

        // jest
        "jest/no-disabled-tests": "warn",
        "jest/no-focused-tests": "error",
        "jest/no-identical-title": "error",
        "jest/prefer-to-have-length": "warn",
        "jest/valid-expect": "error"
    }
}
```

**Comment by SimenB** [comment]
@Ionut-Milas 21.3.2 out

**Comment by Ionut-Milas** [comment]
@SimenB Works now. Thank you !!!
